spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-uat.syndibox.com/realms/Application-ramadan
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ramadan-facade
      principle-attribute: preferred_username


