package com.ramadan.api.config;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import com.ramadan.api.entity.referentiel.Civilite;
import com.ramadan.api.entity.referentiel.Nationalite;
import com.ramadan.api.entity.referentiel.Pays;
import com.ramadan.api.entity.referentiel.Ville;
import com.ramadan.api.repository.referentiel.CiviliteRepository;
import com.ramadan.api.repository.referentiel.NationaliteRepository;
import com.ramadan.api.repository.referentiel.PaysRepository;
import com.ramadan.api.repository.referentiel.VilleRepository;

import jakarta.annotation.PostConstruct;

/**
 * @author ZAROUATI Ayoub
 */

@Profile("init")
@Component
public class DbInit {

	private static final Logger log = LoggerFactory.getLogger(DbInit.class);


	@Autowired
	CiviliteRepository civiliteRepository;

	@Autowired
	NationaliteRepository nationnaliteRepository;

	@Autowired
	VilleRepository villeRepository;

	@Autowired
	PaysRepository paysRepository;

	@PostConstruct
	private void postConstruct() {
		log.info(
				"************************************************************** Lets init DB **************************************************************");
		addCivilite();
		addNationnalite();
		addVille();
		addPays();

	}

	private void addPays() {
		List<Pays> pays = new ArrayList<>();

		pays.add(new Pays("MA", "Maroc"));
		pays.add(new Pays("FR", "France"));

		paysRepository.saveAll(pays);
	}


	private void addCivilite() {

		List<Civilite> civilites = new ArrayList<>();

		civilites.add(new Civilite("M", "Monsieur"));
		civilites.add(new Civilite("Mme", "Madame"));
		civilites.add(new Civilite("Mlle", "Mademoiselle"));

		civiliteRepository.saveAll(civilites);
	}


	private void addNationnalite() {
		List<Nationalite> nationnalites = new ArrayList<>();

		nationnalites.add(new Nationalite("MA", "Maroc"));
		nationnalites.add(new Nationalite("FR", "France"));
		nationnalites.add(new Nationalite("AF", "Afghanistan"));
		nationnalites.add(new Nationalite("ZA", "AfriqueduSud"));
		nationnalites.add(new Nationalite("AL", "Albanie"));
		nationnalites.add(new Nationalite("DZ", "Algérie"));
		nationnalites.add(new Nationalite("DE", "Allemagne"));
		nationnalites.add(new Nationalite("AD", "Andorre"));
		nationnalites.add(new Nationalite("AO", "Angola"));
		nationnalites.add(new Nationalite("AI", "Anguilla"));
		nationnalites.add(new Nationalite("AQ", "Antartica"));
		nationnalites.add(new Nationalite("AG", "AntiguaetBarbuda"));
		nationnalites.add(new Nationalite("AN", "Antilles"));
		nationnalites.add(new Nationalite("AN", "AntillesHollandaises"));
		nationnalites.add(new Nationalite("SA", "Arabiesaoudite"));
		nationnalites.add(new Nationalite("AR", "Argentine"));
		nationnalites.add(new Nationalite("AM", "Arménie"));
		nationnalites.add(new Nationalite("AW", "Aruba"));
		nationnalites.add(new Nationalite("AU", "Australie"));
		nationnalites.add(new Nationalite("AT", "Autriche"));
		nationnalites.add(new Nationalite("AZ", "Azerbaïdjan"));
		nationnalites.add(new Nationalite("BS", "Bahamas"));
		nationnalites.add(new Nationalite("BH", "Bahrein"));
		nationnalites.add(new Nationalite("BD", "Bangladesh"));
		nationnalites.add(new Nationalite("BB", "Barbados"));
		nationnalites.add(new Nationalite("BE", "Belgique"));
		nationnalites.add(new Nationalite("BZ", "Belize"));
		nationnalites.add(new Nationalite("BJ", "Bénin"));
		nationnalites.add(new Nationalite("BM", "Bermudes"));
		nationnalites.add(new Nationalite("BT", "Bhutan"));
		nationnalites.add(new Nationalite("BY", "Biélorussie"));
		nationnalites.add(new Nationalite("BO", "Bolivie"));
		nationnalites.add(new Nationalite("BA", "Bosnie-Herzegovine"));
		nationnalites.add(new Nationalite("BW", "Botswana"));
		nationnalites.add(new Nationalite("BR", "Brésil"));
		nationnalites.add(new Nationalite("IO", "Britishindianoceanterritory"));
		nationnalites.add(new Nationalite("BN", "Bruneidarussalam"));
		nationnalites.add(new Nationalite("BG", "Bulgarie"));
		nationnalites.add(new Nationalite("BF", "BurkinaFaso"));
		nationnalites.add(new Nationalite("BI", "Burundi"));
		nationnalites.add(new Nationalite("KH", "Cambodge"));
		nationnalites.add(new Nationalite("CM", "Cameroun"));
		nationnalites.add(new Nationalite("CA", "Canada"));
		nationnalites.add(new Nationalite("CV", "CapVert"));
		nationnalites.add(new Nationalite("CL", "Chili"));
		nationnalites.add(new Nationalite("CN", "Chine"));
		nationnalites.add(new Nationalite("CY", "Chypre"));
		nationnalites.add(new Nationalite("CC", "Coco(keeling)islands"));
		nationnalites.add(new Nationalite("CO", "Colombie"));
		nationnalites.add(new Nationalite("CG", "Congo"));
		nationnalites.add(new Nationalite("CK", "Cookislands"));
		nationnalites.add(new Nationalite("CR", "CostaRica"));
		nationnalites.add(new Nationalite("CI", "Coted.ivoire"));
		nationnalites.add(new Nationalite("HR", "Croatie"));
		nationnalites.add(new Nationalite("CU", "Cuba"));
		nationnalites.add(new Nationalite("DK", "Danemark"));
		nationnalites.add(new Nationalite("DJ", "Djibouti"));
		nationnalites.add(new Nationalite("DM", "Dominique"));
		nationnalites.add(new Nationalite("EG", "Egypte"));
		nationnalites.add(new Nationalite("EC", "Equateur"));
		nationnalites.add(new Nationalite("ER", "Erythrée"));
		nationnalites.add(new Nationalite("ES", "Espagne"));
		nationnalites.add(new Nationalite("EE", "Estonie"));
		nationnalites.add(new Nationalite("FM", "EtatsFéderalsdeMicronésie"));
		nationnalites.add(new Nationalite("US", "Etats-Unis"));
		nationnalites.add(new Nationalite("ET", "Ethiopie"));
		nationnalites.add(new Nationalite("RU", "FédérationRusse"));
		nationnalites.add(new Nationalite("FI", "Finlande"));
		nationnalites.add(new Nationalite("TF", "Frenchsouthernterritories"));
		nationnalites.add(new Nationalite("GA", "Gabon"));
		nationnalites.add(new Nationalite("GM", "Gambie"));
		nationnalites.add(new Nationalite("GE", "Georgie"));
		nationnalites.add(new Nationalite("GH", "Ghana"));
		nationnalites.add(new Nationalite("GI", "Gibraltar"));
		nationnalites.add(new Nationalite("GB", "Grande-Bretagne"));
		nationnalites.add(new Nationalite("GR", "Grèce"));
		nationnalites.add(new Nationalite("GL", "Greenland"));
		nationnalites.add(new Nationalite("GD", "Grenade"));
		nationnalites.add(new Nationalite("GP", "Guadeloupe"));
		nationnalites.add(new Nationalite("GU", "Guam"));
		nationnalites.add(new Nationalite("GT", "Guatemala"));
		nationnalites.add(new Nationalite("GG", "Guernsey,C.I."));
		nationnalites.add(new Nationalite("GN", "Guinée"));
		nationnalites.add(new Nationalite("GQ", "GuinéeEquatoriale"));
		nationnalites.add(new Nationalite("GW", "Guinée-Bissau"));
		nationnalites.add(new Nationalite("GY", "Guyane"));
		nationnalites.add(new Nationalite("GF", "GuyaneFrançaise"));
		nationnalites.add(new Nationalite("HT", "Haiti"));
		nationnalites.add(new Nationalite("HM", "HeardandMcdonaldIslands"));
		nationnalites.add(new Nationalite("HN", "Honduras"));
		nationnalites.add(new Nationalite("HK", "Hongkong"));
		nationnalites.add(new Nationalite("HU", "Hongrie"));
		nationnalites.add(new Nationalite("IS", "Iceland"));
		nationnalites.add(new Nationalite("BV", "IleBouvet"));
		nationnalites.add(new Nationalite("IM", "IledeMan"));
		nationnalites.add(new Nationalite("MU", "IleMaurice"));
		nationnalites.add(new Nationalite("NF", "IleNorfolk"));
		nationnalites.add(new Nationalite("KY", "IlesCaymanes"));
		nationnalites.add(new Nationalite("KM", "Ilescommore"));
		nationnalites.add(new Nationalite("CX", "IlesdePaques"));
		nationnalites.add(new Nationalite("FO", "IlesFaeroe"));
		nationnalites.add(new Nationalite("FJ", "IlesFidji"));
		nationnalites.add(new Nationalite("FK", "IlesMalouines"));
		nationnalites.add(new Nationalite("MH", "IlesMarshall"));
		nationnalites.add(new Nationalite("IN", "Inde"));
		nationnalites.add(new Nationalite("ID", "Indonésie"));
		nationnalites.add(new Nationalite("IR", "Iran"));
		nationnalites.add(new Nationalite("IQ", "Iraq"));
		nationnalites.add(new Nationalite("IE", "Irlande"));
		nationnalites.add(new Nationalite("IL", "Israel"));
		nationnalites.add(new Nationalite("IT", "Italie"));
		nationnalites.add(new Nationalite("LY", "JamahiriyaArabedeLibye"));
		nationnalites.add(new Nationalite("JM", "Jamaique"));
		nationnalites.add(new Nationalite("JP", "Japon"));
		nationnalites.add(new Nationalite("JE", "Jersey,C.I."));
		nationnalites.add(new Nationalite("JO", "Jordanie"));
		nationnalites.add(new Nationalite("KZ", "Kazakhstan"));
		nationnalites.add(new Nationalite("KE", "Kenya"));
		nationnalites.add(new Nationalite("KG", "Kirdjistan"));
		nationnalites.add(new Nationalite("KI", "Kiribati"));
		nationnalites.add(new Nationalite("KW", "Koweit"));
		nationnalites.add(new Nationalite("LV", "Latvia"));
		nationnalites.add(new Nationalite("LS", "Lesotho"));
		nationnalites.add(new Nationalite("LB", "Liban"));
		nationnalites.add(new Nationalite("LR", "Liberia"));
		nationnalites.add(new Nationalite("LI", "Liechtenstein"));
		nationnalites.add(new Nationalite("LT", "Lituanie"));
		nationnalites.add(new Nationalite("LU", "Luxembourg"));
		nationnalites.add(new Nationalite("MO", "Macao"));
		nationnalites.add(new Nationalite("MK", "Macédoine"));
		nationnalites.add(new Nationalite("MG", "Madagascar"));
		nationnalites.add(new Nationalite("MY", "Malaisie"));
		nationnalites.add(new Nationalite("Mw", "Malaisie"));
		nationnalites.add(new Nationalite("MV", "Maldives"));
		nationnalites.add(new Nationalite("ML", "Mali"));
		nationnalites.add(new Nationalite("MT", "Malte"));
		nationnalites.add(new Nationalite("MQ", "Martinique"));
		nationnalites.add(new Nationalite("MR", "Mauritanie"));
		nationnalites.add(new Nationalite("MT", "Mayotte"));
		nationnalites.add(new Nationalite("MX", "Mexique"));
		nationnalites.add(new Nationalite("MC", "Monaco"));
		nationnalites.add(new Nationalite("MN", "Mongolie"));
		nationnalites.add(new Nationalite("MS", "Montserrat"));
		nationnalites.add(new Nationalite("MZ", "Mozambique"));
		nationnalites.add(new Nationalite("MM", "Myanmar"));
		nationnalites.add(new Nationalite("NA", "Namibie"));
		nationnalites.add(new Nationalite("NR", "Nauru"));
		nationnalites.add(new Nationalite("NP", "Nepal"));
		nationnalites.add(new Nationalite("NI", "Nicaragua"));
		nationnalites.add(new Nationalite("NE", "Niger"));
		nationnalites.add(new Nationalite("NG", "Nigeria"));
		nationnalites.add(new Nationalite("NU", "Niue"));
		nationnalites.add(new Nationalite("MP", "NorthernMarianaIslands"));
		nationnalites.add(new Nationalite("NO", "Norvège"));
		nationnalites.add(new Nationalite("NC", "NouvelleCalédonie"));
		nationnalites.add(new Nationalite("NZ", "Nouvelle-Zélande"));
		nationnalites.add(new Nationalite("OM", "Oman"));
		nationnalites.add(new Nationalite("UZ", "Ouzbekistan"));
		nationnalites.add(new Nationalite("PK", "Pakistan"));
		nationnalites.add(new Nationalite("PW", "Palau"));
		nationnalites.add(new Nationalite("PA", "Panama"));
		nationnalites.add(new Nationalite("PZ", "Panamacanalzone"));
		nationnalites.add(new Nationalite("PG", "PapuaNewGuinea"));
		nationnalites.add(new Nationalite("PY", "Paraguay"));
		nationnalites.add(new Nationalite("NL", "PaysBas"));
		nationnalites.add(new Nationalite("PE", "Pérou"));
		nationnalites.add(new Nationalite("PH", "Philippines"));
		nationnalites.add(new Nationalite("PN", "Pitcaim"));
		nationnalites.add(new Nationalite("PL", "Pologne"));
		nationnalites.add(new Nationalite("PF", "PolynésieFrancaise"));
		nationnalites.add(new Nationalite("PR", "PortoRico"));
		nationnalites.add(new Nationalite("PT", "Portugal"));
		nationnalites.add(new Nationalite("QA", "Qatar"));
		nationnalites.add(new Nationalite("SY", "RépubliquearabedeSyrie"));
		nationnalites.add(new Nationalite("CF", "RépubliquedecentreAfrique"));
		nationnalites.add(new Nationalite("KR", "RépubliquedeCorée"));
		nationnalites.add(new Nationalite("MD", "RépubliquedeMoldavie"));
		nationnalites.add(new Nationalite("CZ", "Républiquedetchéquie"));
		nationnalites.add(new Nationalite("ZR", "RépubliquedémocratiquedeCongo"));
		nationnalites.add(new Nationalite("KP", "RépubliquedémocratiquedupeopledeCorée"));
		nationnalites.add(new Nationalite("LA", "RépubliquedémocratiquedupeopledeLao"));
		nationnalites.add(new Nationalite("DO", "Républiquedominicaine"));
		nationnalites.add(new Nationalite("TZ", "RépubliqueUniedeTanzanie"));
		nationnalites.add(new Nationalite("RE", "Réunion"));
		nationnalites.add(new Nationalite("RO", "Romanie"));
		nationnalites.add(new Nationalite("RW", "Rwanda"));
		nationnalites.add(new Nationalite("KN", "SaintKittsandNevis"));
		nationnalites.add(new Nationalite("LC", "SaintLucia"));
		nationnalites.add(new Nationalite("VC", "SaintVincentandTheGrenadines"));
		nationnalites.add(new Nationalite("SV", "Salvador"));
		nationnalites.add(new Nationalite("WS", "Samoa"));
		nationnalites.add(new Nationalite("SM", "SanMarino"));
		nationnalites.add(new Nationalite("ST", "SaoTomeandPrincipe"));
		nationnalites.add(new Nationalite("SN", "Senegal"));
		nationnalites.add(new Nationalite("SC", "Seychelles"));
		nationnalites.add(new Nationalite("SL", "SierraLeone"));
		nationnalites.add(new Nationalite("SG", "Singapour"));
		nationnalites.add(new Nationalite("SK", "Slovaquie"));
		nationnalites.add(new Nationalite("SI", "Slovénie"));
		nationnalites.add(new Nationalite("SB", "SolomonIslands"));
		nationnalites.add(new Nationalite("SO", "Somalie"));
		nationnalites.add(new Nationalite("SD", "Soudan"));
		nationnalites.add(new Nationalite("GS", "SouthGeorgiaandsouthsandwichislands"));
		nationnalites.add(new Nationalite("LK", "SriLanka"));
		nationnalites.add(new Nationalite("SH", "St.Helena"));
		nationnalites.add(new Nationalite("Pm", "St.PierreandMiquelon"));
		nationnalites.add(new Nationalite("SE", "Suede"));
		nationnalites.add(new Nationalite("CH", "Suisse"));
		nationnalites.add(new Nationalite("SR", "Surinam"));
		nationnalites.add(new Nationalite("SJ", "SvalbardendjanmayenIslands"));
		nationnalites.add(new Nationalite("SZ", "Swaziland"));
		nationnalites.add(new Nationalite("TW", "Taiwan"));
		nationnalites.add(new Nationalite("TJ", "Tajikistan"));
		nationnalites.add(new Nationalite("TD", "Tchad"));
		nationnalites.add(new Nationalite("CZ", "Tchéquie"));
		nationnalites.add(new Nationalite("TH", "Thailand"));
		nationnalites.add(new Nationalite("TP", "Timordel.est"));
		nationnalites.add(new Nationalite("TG", "Togo"));
		nationnalites.add(new Nationalite("TK", "Tokelau"));
		nationnalites.add(new Nationalite("TO", "Tonga"));
		nationnalites.add(new Nationalite("TT", "TrinidadandTobago"));
		nationnalites.add(new Nationalite("TN", "Tunisie"));
		nationnalites.add(new Nationalite("TR", "Turquie"));
		nationnalites.add(new Nationalite("UY", "Uruguay"));
		nationnalites.add(new Nationalite("VU", "Vanuatu"));
		nationnalites.add(new Nationalite("VA", "Vatican"));
		nationnalites.add(new Nationalite("VE", "Venezuela"));
		nationnalites.add(new Nationalite("ZM", "Zambie"));
		nationnalites.add(new Nationalite("ZW", "Zimbabwe"));

		nationnalites.forEach(nationalite -> nationnaliteRepository.save(nationalite));
	}

	private void addVille() {
		List<Ville> villes = new ArrayList<>();
		villes.add(new Ville("1", "RABAT"));
		villes.add(new Ville("2", "CASABLANCA"));
		villes.add(new Ville("3", "TANGER"));
		villes.add(new Ville("4", "MARRAKECH"));
		villes.add(new Ville("5", "TETOUAN"));
		villes.add(new Ville("6", "FES"));
		villes.add(new Ville("7", "MEKNES"));
		villes.add(new Ville("8", "SAFI"));
		villes.add(new Ville("9", "EL JADIDA"));
		villes.add(new Ville("10", "AGADIR"));
		villes.add(new Ville("11", "BOUJAAD"));
		villes.add(new Ville("12", "OUED ZEM"));
		villes.add(new Ville("13", "KASBA TADLA"));
		villes.add(new Ville("14", "MOHAMMADIA"));
		villes.add(new Ville("15", "KENITRA"));
		villes.add(new Ville("16", "SETTAT"));
		villes.add(new Ville("17", "OUJDA"));
		villes.add(new Ville("18", "TAZA"));
		villes.add(new Ville("19", "KHENIFRA"));
		villes.add(new Ville("20", "KHOURIBGA"));
		villes.add(new Ville("21", "OULED NEMMA"));
		villes.add(new Ville("22", "BERKANE"));
		villes.add(new Ville("23", "KSAR LEKBIR"));
		villes.add(new Ville("24", "ESSAOUIRA"));
		villes.add(new Ville("25", "ERFOUD"));
		villes.add(new Ville("26", "LARACHE"));
		villes.add(new Ville("27", "BEN SLIMANE"));
		villes.add(new Ville("28", "NADOR"));
		villes.add(new Ville("29", "SIDI SLIMANE"));
		villes.add(new Ville("30", "TIFLET"));
		villes.add(new Ville("31", "RICH"));
		villes.add(new Ville("32", "KALAA S'RAGHNA"));
		villes.add(new Ville("33", "BENI MELLAL"));
		villes.add(new Ville("34", "MIDELT"));
		villes.add(new Ville("35", "ERRACHIDIA"));
		villes.add(new Ville("36", "BIR J'DID"));
		villes.add(new Ville("37", "AZROU"));
		villes.add(new Ville("38", "KHEMISSET"));
		villes.add(new Ville("39", "BERRECHID"));
		villes.add(new Ville("40", "SOUK EL ARBAA DU GHARB"));
		villes.add(new Ville("41", "BEN GUERIR"));
		villes.add(new Ville("42", "OUARZAZATE"));
		villes.add(new Ville("43", "IFNI"));
		villes.add(new Ville("44", "AIN BENI MATHAR"));
		villes.add(new Ville("45", "JERADA"));
		villes.add(new Ville("46", "ASILAH"));
		villes.add(new Ville("47", "OUEZZANE"));
		villes.add(new Ville("48", "CHEMMAIA"));
		villes.add(new Ville("49", "SIDI KACEM"));
		villes.add(new Ville("50", "AZEMMOUR"));
		villes.add(new Ville("51", "FKIH BEN SALAH"));
		villes.add(new Ville("52", "SIDI BENNOUR"));
		villes.add(new Ville("53", "TIZNIT"));
		villes.add(new Ville("54", "TAROUDANT"));
		villes.add(new Ville("55", "MECHRAA BEL KSIRI"));
		villes.add(new Ville("56", "M'RIRT"));
		villes.add(new Ville("57", "YOUSSOUFIA"));
		villes.add(new Ville("58", "SIDI MOKHTAR"));
		villes.add(new Ville("59", "TAOUNATE"));
		villes.add(new Ville("60", "ZAGORA"));
		villes.add(new Ville("61", "SEFROU"));
		villes.add(new Ville("62", "TAN TAN"));
		villes.add(new Ville("63", "EL HAJEB"));
		villes.add(new Ville("64", "LAAYOUNE"));
		villes.add(new Ville("65", "AZILAL"));
		villes.add(new Ville("66", "RISSANI"));
		villes.add(new Ville("67", "TASSILA MASSA"));
		villes.add(new Ville("68", "TINGHIR"));
		villes.add(new Ville("69", "DEMNATE"));
		villes.add(new Ville("70", "OULAD TEIMA"));
		villes.add(new Ville("71", "BEN AHMED"));
		villes.add(new Ville("72", "ZAOUIA CHEIKH"));
		villes.add(new Ville("73", "AL HOCEIMA"));
		villes.add(new Ville("74", "CHAOUEN"));
		villes.add(new Ville("75", "AIT BAHA"));
		villes.add(new Ville("76", "GUELMIM"));
		villes.add(new Ville("77", "TALIOUINE"));
		villes.add(new Ville("78", "BOUZNIKA"));
		villes.add(new Ville("79", "AKKA"));
		villes.add(new Ville("80", "CHICHAOUA"));
		villes.add(new Ville("81", "KHMIS ZMAMRA"));
		villes.add(new Ville("82", "BOUYAZAKARNE"));
		villes.add(new Ville("83", "AIT MELLOUL"));
		villes.add(new Ville("84", "MISSOUR"));
		villes.add(new Ville("85", "IMINE TANOUTE"));
		villes.add(new Ville("86", "OUAOUIZERTH"));
		villes.add(new Ville("87", "AGDZ"));
		villes.add(new Ville("88", "ESSAMARA"));
		villes.add(new Ville("89", "EL GARA"));
		villes.add(new Ville("90", "TIT MELLIL"));
		villes.add(new Ville("91", "MEDIOUNA"));
		villes.add(new Ville("92", "AIN JMEL"));
		villes.add(new Ville("93", "TNINE"));
		villes.add(new Ville("94", "CHTOUK"));
		villes.add(new Ville("95", "HAD OULAD FREJ"));
		villes.add(new Ville("96", "SIDI SMAIL"));
		villes.add(new Ville("97", "OUALIDIA"));
		villes.add(new Ville("98", "KASBA BOULAOUANE"));
		villes.add(new Ville("99", "OULAD BOUZITI"));
		villes.add(new Ville("100", "GUISSER"));
		villes.add(new Ville("101", "MECHRA BEN ABBOU"));
		villes.add(new Ville("102", "SKHOUR RHARMA"));
		villes.add(new Ville("103", "JEMAA SHAIM"));
		villes.add(new Ville("104", "TLETA BOUGEDRA"));
		villes.add(new Ville("105", "SEBT GZOULA"));
		villes.add(new Ville("106", "SIDI BOU OTHMANE"));
		villes.add(new Ville("107", "TALMEST"));
		villes.add(new Ville("108", "OUNARA"));
		villes.add(new Ville("109", "TLETA HANCHANE"));
		villes.add(new Ville("110", "TAMELELT"));
		villes.add(new Ville("111", "AIT OURIR"));
		villes.add(new Ville("112", "TAHANOUATE"));
		villes.add(new Ville("113", "TADDERT"));
		villes.add(new Ville("114", "TIZIN TICHKA"));
		villes.add(new Ville("115", "TALOUET"));
		villes.add(new Ville("116", "AMIZMIZ"));
		villes.add(new Ville("117", "OUKAIMEDEN"));
		villes.add(new Ville("118", "IJOUKAK"));
		villes.add(new Ville("119", "AIT BEN HADDOU"));
		villes.add(new Ville("120", "TAMRI"));
		villes.add(new Ville("121", "TAOURIRT"));
		villes.add(new Ville("122", "AOULOUZ"));
		villes.add(new Ville("123", "INEZGANE"));
		villes.add(new Ville("124", "TAZNAKHT"));
		villes.add(new Ville("125", "BIOUGRA"));
		villes.add(new Ville("126", "FARCIA"));
		villes.add(new Ville("127", "IRHERM"));
		villes.add(new Ville("128", "TAFRAOUTE"));
		villes.add(new Ville("129", "ZAIO"));
		villes.add(new Ville("130", "SIDI ALLAL TAZI"));
		villes.add(new Ville("131", "SIDI YAHIA DU GHARB"));
		villes.add(new Ville("132", "BOUKNADEL"));
		villes.add(new Ville("133", "DAR EL AMRI"));
		villes.add(new Ville("134", "SIDI ALLAL BAHNAOUI"));
		villes.add(new Ville("135", "SIDI YAHIA ZAER"));
		villes.add(new Ville("136", "AIN AOUDA"));
		villes.add(new Ville("137", "LOUIZIA"));
		villes.add(new Ville("138", "MAAZIZ"));
		villes.add(new Ville("139", "SIDI BETACH"));
		villes.add(new Ville("140", "TIDDAS"));
		villes.add(new Ville("141", "ROMMANI"));
		villes.add(new Ville("142", "EL HANCHA"));
		villes.add(new Ville("143", "OULMES"));
		villes.add(new Ville("144", "EZ ZHILIGA"));
		villes.add(new Ville("145", "EL KHATOUAT"));
		villes.add(new Ville("146", "EL KSIBA"));
		villes.add(new Ville("147", "DAR OULD ZIDOUH"));
		villes.add(new Ville("148", "EL KBAB"));
		villes.add(new Ville("149", "BZOU"));
		villes.add(new Ville("150", "AFOURER"));
		villes.add(new Ville("151", "BIN EL OUIDANE"));
		villes.add(new Ville("152", "KELAA MGOUNA"));
		villes.add(new Ville("153", "TINRHRIR"));
		villes.add(new Ville("154", "SKOURA"));
		villes.add(new Ville("155", "BEN KARICH"));
		villes.add(new Ville("156", "EL BAHRI"));
		villes.add(new Ville("157", "SOUK LARBAA BNI HASSAN"));
		villes.add(new Ville("158", "FIGUIG"));
		villes.add(new Ville("159", "CHEFCHAOUEN"));
		villes.add(new Ville("160", "BAB TAZA"));
		villes.add(new Ville("161", "ZOUMI"));
		villes.add(new Ville("162", "TARGUIST"));
		villes.add(new Ville("163", "BOURED"));
		villes.add(new Ville("164", "HAD-KOURT"));
		villes.add(new Ville("165", "TAHAR-SOUK"));
		villes.add(new Ville("166", "RHAFSAI"));
		villes.add(new Ville("167", "FES-EL-BALI"));
		villes.add(new Ville("168", "OURTZAGH"));
		villes.add(new Ville("169", "TAINESTE"));
		villes.add(new Ville("170", "AIN AICHA"));
		villes.add(new Ville("171", "TISSA"));
		villes.add(new Ville("172", "MOULAY DRISS ZERHOUNE"));
		villes.add(new Ville("173", "SIDI ABDELLAH-DES-GHAITA"));
		villes.add(new Ville("174", "ABJELIL"));
		villes.add(new Ville("175", "TAHALA"));
		villes.add(new Ville("176", "SIDI HRAZEM"));
		villes.add(new Ville("177", "RAS-EL-MA"));
		villes.add(new Ville("178", "BOUFEKRANE"));
		villes.add(new Ville("179", "BHALIL"));
		villes.add(new Ville("180", "EL MENZEL"));
		villes.add(new Ville("181", "IMOUZZER DU KANDAR"));
		villes.add(new Ville("182", "IFRANE"));
		villes.add(new Ville("183", "MICHLIFFEN"));
		villes.add(new Ville("184", "BOULEMANE"));
		villes.add(new Ville("185", "AIN LEUH"));
		villes.add(new Ville("186", "TIMAHDITE"));
		villes.add(new Ville("187", "BOUMIA"));
		villes.add(new Ville("188", "KSABI"));
		villes.add(new Ville("189", "GOURRAMA"));
		villes.add(new Ville("190", "TATA"));
		villes.add(new Ville("191", "GOULMIMA"));
		villes.add(new Ville("192", "ITZER"));
		villes.add(new Ville("193", "AIT YOUSSEF-OU-ALI"));
		villes.add(new Ville("194", "BNI-ENZAR"));
		villes.add(new Ville("195", "SEGANGANE"));
		villes.add(new Ville("196", "MIDAR"));
		villes.add(new Ville("197", "SAIDIA"));
		villes.add(new Ville("198", "MECHRA SAFSAF"));
		villes.add(new Ville("199", "AHFIR"));
		villes.add(new Ville("200", "EL AIOUN"));
		villes.add(new Ville("202", "MSOUM"));
		villes.add(new Ville("203", "GUERCIF"));
		villes.add(new Ville("204", "DEBDOU"));
		villes.add(new Ville("205", "BNI SNASSEN"));
		villes.add(new Ville("206", "OUTAT OULED EL HADJ"));
		villes.add(new Ville("207", "BOUARFA"));
		villes.add(new Ville("208", "TALSIMT"));
		villes.add(new Ville("209", "ADDAKHLA"));
		villes.add(new Ville("210", "LAGWIRA"));
		villes.add(new Ville("211", "BNI ANZARANE"));
		villes.add(new Ville("212", "TARFAYA"));
		villes.add(new Ville("213", "TANALT"));
		villes.add(new Ville("214", "TAFILALT"));
		villes.add(new Ville("215", "BROUJ"));
		villes.add(new Ville("216", "KARIAT BA MOHAMED"));
		villes.add(new Ville("217", "BELKSIRI"));
		villes.add(new Ville("218", "SOUK SEBT"));
		villes.add(new Ville("219", "SIDI MOUSSA BEN ALI"));
		villes.add(new Ville("220", "SIDI HAJJAJ"));
		villes.add(new Ville("221", "BOUJDOUR"));
		villes.add(new Ville("222", "TEMANAR"));
		villes.add(new Ville("223", "MOGRANE"));
		villes.add(new Ville("224", "DOUAR AMAHROQ"));
		villes.add(new Ville("225", "AGOURAI"));
		villes.add(new Ville("227", "HAD BRACHOUA"));
		villes.add(new Ville("228", "TICHLA"));
		villes.add(new Ville("229", "TOUKAT NAKHLA"));
		villes.add(new Ville("230", "FAM EL HSIN"));
		villes.add(new Ville("231", "AKNOUL"));
		villes.add(new Ville("232", "BOUKRAA"));
		villes.add(new Ville("233", "AMGALA"));
		villes.add(new Ville("234", "OUED EDDAHAB"));
		villes.add(new Ville("235", "TEMERA"));
		villes.add(new Ville("236", "SALE"));
		villes.add(new Ville("238", "ASSA ZAG"));
		villes.add(new Ville("581", "BENI DRAR"));
		villes.add(new Ville("821", "SKHIRAT"));
		villes.add(new Ville("999", "AUTRES"));

		villeRepository.saveAll(villes);

	}

}
